### ISSUE TITLE
Pieces can be held during countdown

### ISSUE THREAD

**Issue by voytxt** [MrakDun-desu/BlockStacker-desu#12]
1. Play any gamemode
2. When the counter is ticking down, press hold
3. Now you can kinda manipulate the piece (while the timer is still ticking down), and break a lot of stuff, just by mashing buttons :P

If you're successful with button mashing, u can get the piece stuck there even after you restart (I piece from previous game)
![image](https://user-images.githubusercontent.com/65811166/204621212-6f7f1d87-622f-4bdc-9d72-381cf72a2304.png)

But it's just the texture, it isn't actually there (placed a T on it here)
![image](https://user-images.githubusercontent.com/65811166/204621375-19bddf38-c0ae-40cf-8380-22f0960ccb75.png)

Also pieces can disappear sometimes after doing this (they work and display correctly when you get to them, but don't show up in the queue)
![image](https://user-images.githubusercontent.com/65811166/204621604-38541d80-1fb4-4b78-a26e-e65f76f26da7.png)

**Comment by MrakDun-desu** [comment]
Inputs were enabled before the game even started. Should be fixed in the latest release. Check itch.io

**Comment by voytxt** [comment]
This issue still persists after the game gets restarted:

1. Play any gamemode
2. Press restart
3. When the counter is ticking down, press hold

**Comment by MrakDun-desu** [comment]
Fixed in 0.31.
